# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mitsuaki/unsw/18s1/cs4601/imageCompression/designprojectb/WavletVHDL/imagecompression/imagecompression.srcs/sources_1/bd/system/ip/system_axi_ip_demo_0_0/system_axi_ip_demo_0_0.xci
# IP: The module: 'system_axi_ip_demo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/mitsuaki/unsw/18s1/cs4601/imageCompression/designprojectb/WavletVHDL/imagecompression/imagecompression.srcs/sources_1/bd/system/ip/system_axi_ip_demo_0_0/src/floating_point_0_1/floating_point_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_0 || ORIG_REF_NAME==floating_point_0}]

# IP: /home/mitsuaki/unsw/18s1/cs4601/imageCompression/designprojectb/WavletVHDL/imagecompression/imagecompression.srcs/sources_1/bd/system/ip/system_axi_ip_demo_0_0/src/floating_point_add_1/floating_point_add.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_add || ORIG_REF_NAME==floating_point_add}]

# IP: /home/mitsuaki/unsw/18s1/cs4601/imageCompression/designprojectb/WavletVHDL/imagecompression/imagecompression.srcs/sources_1/bd/system/ip/system_axi_ip_demo_0_0/src/floating_point_1_1/floating_point_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_1 || ORIG_REF_NAME==floating_point_1}]

# IP: /home/mitsuaki/unsw/18s1/cs4601/imageCompression/designprojectb/WavletVHDL/imagecompression/imagecompression.srcs/sources_1/bd/system/ip/system_axi_ip_demo_0_0/system_axi_ip_demo_0_0.xci
# IP: The module: 'system_axi_ip_demo_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/mitsuaki/unsw/18s1/cs4601/imageCompression/designprojectb/WavletVHDL/imagecompression/imagecompression.srcs/sources_1/bd/system/ip/system_axi_ip_demo_0_0/src/floating_point_0_1/floating_point_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_0 || ORIG_REF_NAME==floating_point_0}]

# IP: /home/mitsuaki/unsw/18s1/cs4601/imageCompression/designprojectb/WavletVHDL/imagecompression/imagecompression.srcs/sources_1/bd/system/ip/system_axi_ip_demo_0_0/src/floating_point_add_1/floating_point_add.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_add || ORIG_REF_NAME==floating_point_add}]

# IP: /home/mitsuaki/unsw/18s1/cs4601/imageCompression/designprojectb/WavletVHDL/imagecompression/imagecompression.srcs/sources_1/bd/system/ip/system_axi_ip_demo_0_0/src/floating_point_1_1/floating_point_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_1 || ORIG_REF_NAME==floating_point_1}]
