# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/mitsuaki/unsw/18s1/cs4601/imageCompression/designprojectb/WavletVHDL/ip_repo/axi_ip_demo_1.0/src/floating_point_0_1/floating_point_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_0 || ORIG_REF_NAME==floating_point_0}]

# IP: /home/mitsuaki/unsw/18s1/cs4601/imageCompression/designprojectb/WavletVHDL/ip_repo/axi_ip_demo_1.0/src/floating_point_add_1/floating_point_add.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_add || ORIG_REF_NAME==floating_point_add}]

# IP: /home/mitsuaki/unsw/18s1/cs4601/imageCompression/designprojectb/WavletVHDL/ip_repo/axi_ip_demo_1.0/src/floating_point_1_1/floating_point_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==floating_point_1 || ORIG_REF_NAME==floating_point_1}]
